# Generated by Django 3.1.4 on 2020-12-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0003_auto_20201224_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avdevices',
            old_name='avdevices_name',
            new_name='av_name',
        ),
        migrations.RenameField(
            model_name='avdevices',
            old_name='avdevices_price',
            new_name='av_price',
        ),
    ]
