# Generated by Django 3.1.4 on 2020-12-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0004_auto_20201225_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('card_number', models.IntegerField(null=True)),
                ('expiration', models.DateTimeField(blank=True)),
            ],
        ),
    ]
