# Generated by Django 3.1.4 on 2020-12-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
